### ISSUE TITLE
SQL statements to convert enum and json fields not shown for MySQL DB

### ISSUE THREAD

**Issue by nikolasburk** [prisma/upgrade#83]
I'm currently going through the upgrade process but the SQL statements to convert `TEXT` to `enum` and `json` types are not shown.

Here's my Prisma 1 datamodel:

```graphql
type User {
  id: ID! @id
  email: String @unique
  name: String!
  role: Role! @default(value: CUSTOMER)
  jsonData: Json 
  profile: Profile
  posts: [Post!]!
}
type Post {
  id: ID! @id
  createdAt: DateTime! @createdAt
  updatedAt: DateTime! @updatedAt
  title: String!
  content: String
  published: Boolean! @default(value: false)
  author: User @relation(link: TABLE)
  categories: [Category!]!
}
type Profile {
  id: ID! @id
  bio: String
  user: User! @relation(link: INLINE)
}
type Category {
  id: ID! @id
  name: String!
  posts: [Post!]!
}
enum Role {
  ADMIN
  CUSTOMER
}
```

After the initial introspection, I directly ran:

```
npx prisma-upgrade prisma1/prisma.yml prisma/schema.prisma
```

The JSON and enum conversions were then missing from the generated SQL:

```
➤ Adjust your database schema
Run the following SQL statements against your database:

  Add missing `DEFAULT` constraints to the database
  https://pris.ly/d/schema-incompatibilities#default-values-arent-represented-in-database

    ALTER TABLE `User` CHANGE `role` `role` ENUM('ADMIN', 'CUSTOMER') NOT NULL DEFAULT 'CUSTOMER';
    ALTER TABLE `Post` CHANGE `published` `published` TINYINT(1) NOT NULL DEFAULT 0;


  Replicate `@createdAt` behavior in Prisma 2
  https://pris.ly/d/schema-incompatibilities#createdat-isnt-represented-in-database

    ALTER TABLE `Post` CHANGE `createdAt` `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;


  Fix 1-1 relations by adding `UNIQUE` constraints
  https://pris.ly/d/schema-incompatibilities#inline-1-1-relations-are-recognized-as-1-n-missing-unique-constraint

    ALTER TABLE `Profile` ADD UNIQUE (`user`);


  Migrate IDs from varchar(25) to varchar(30)
  https://pris.ly/d/schema-incompatibilities#mismatching-cuid-length

    SET FOREIGN_KEY_CHECKS=0;
    ALTER TABLE `Category` CHANGE `id` `id` char(30) CHARACTER SET utf8 NOT NULL;
    ALTER TABLE `Post` CHANGE `id` `id` char(30) CHARACTER SET utf8 NOT NULL;
    ALTER TABLE `Profile` CHANGE `id` `id` char(30) CHARACTER SET utf8 NOT NULL;
    ALTER TABLE `Profile` CHANGE `user` `user` char(30) CHARACTER SET utf8 ;
    ALTER TABLE `User` CHANGE `id` `id` char(30) CHARACTER SET utf8 NOT NULL;
    SET FOREIGN_KEY_CHECKS=1;
```

They also didn't appear in the "breaking changes section":

```
➤ Adjust your database schema (these changes break Prisma 1)
Run the following SQL statements against your database:

  Fix one-to-many table relations
  https://pris.ly/d/schema-incompatibilities#all-non-inline-relations-are-recognized-as-m-n

    ALTER TABLE `Post` ADD COLUMN `authorId` char(30) CHARACTER SET utf8;
    UPDATE `Post`, `_PostToUser` SET `Post`.`authorId` = `_PostToUser`.B where `_PostToUser`.A = `Post`.`id`;
    ALTER TABLE `Post` ADD FOREIGN KEY (`authorId`) REFERENCES `User`(`id`);
    DROP TABLE `_PostToUser`;



➤ Next Steps

After you executed one or more of the previous SQL statements against your database,
please run the following two commands to refresh your Prisma 2 schema and check
the changes.

  1. Run `npx prisma introspect` again to refresh your Prisma 2 schema.
  2. Run `npx prisma-upgrade` again.

If you can't or don't want to execute the remaining SQL statements right now, you can
skip to the last step where the Upgrade CLI adds missing attributes to your Prisma 2
schema that are not picked up by introspection.
    
Skip to the last step? [Y/n]? 
```

**Comment by matthewmueller** [comment]
Fixed in `0.0.42`

**Comment by smschick** [comment]
Attempting this same scenario with `0.0.42` and can confirm it is still not providing the appropriate SQL statements, not in the breaking changes section either.
